<a href="https://colab.research.google.com/github/GabboM/NNDS/blob/master/S_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Neural Networks for Data Science Applications

Code and work is related to this [Paper](https://arxiv.org/pdf/1805.02474.pdf)
and some code is adapted from [here](https://keras.io/examples/nlp/pretrained_word_embeddings/) and [here](https://medium.com/softmax/tensorflow-keras-lstm-source-code-line-by-line-explained-125a6dae0622)

In [2]:
import tensorflow_datasets as tfds
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
from tensorflow.python.keras import backend as K
from tensorflow.keras.activations import sigmoid
from tensorflow.keras.activations import tanh

import numpy as np
import os

# Data

### Loading IMDB_reviews and splitting in Train/Test

In [ ]:
(ds_train, ds_test), ds_info = tfds.load('imdb_reviews/plain_text',
                                          split=['train', 'test'],
                                          shuffle_files=True,
                                          as_supervised=True,
                                          with_info=True)

creating a list `ds` of all the reviews in plain text

In [ ]:
it = list(ds_train)
ds = []
for i in it:
  ds.append(i[0].numpy().decode())

Let's download the GloVe word embeddings. We will use dim=100 instead of 300 to speed up the training

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

--2020-09-05 12:49:50--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-09-05 12:49:50--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-09-05 12:49:50--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.2’

glove

creating a mapping of the words to their vector representation by GloVe

In [ ]:
path_to_glove_file = os.path.join(
    "glove.6B.100d.txt"
)

embeddings_index = {}
with open(path_to_glove_file) as f:
    for line in f:
        word, coefs = line.split(maxsplit=1)
        coefs = np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word] = coefs

print("Found %s word vectors." % len(embeddings_index))

Found 400000 word vectors.


Now we should have a tokenizer for the raw text. We train a word tokenizer on the training corpus and create a dictionary with the corresponding vocabulary

In [ ]:
text_dataset = tf.data.Dataset.from_tensor_slices(ds)
max_features = 20000  # Maximum vocab size.
max_len = 200  # Sequence length to pad the outputs to.

# Create the layer.
vectorize = TextVectorization(
 max_tokens=max_features,
 output_mode='int',
 output_sequence_length=max_len)

# Now that the vocab layer has been created, call `adapt` on the text-only
# dataset to create the vocabulary. You don't have to batch, but for large
# datasets this means we're not keeping spare copies of the dataset.
vectorize.adapt(text_dataset.batch(64))

In [ ]:
voc = vectorize.get_vocabulary()
word_index = dict(zip(voc, range(len(voc))))

creating an embedding matrix

In [ ]:
num_tokens = len(voc) + 2
embedding_dim = 100
hits = 0
misses = 0

# Prepare embedding matrix
embedding_matrix = np.zeros((num_tokens, embedding_dim))
for word, i in word_index.items():
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        # Words not found in embedding index will be all-zeros.
        # This includes the representation for "padding" and "OOV"
        embedding_matrix[i] = embedding_vector
        hits += 1
    else:
        misses += 1
print("Converted %d words (%d misses)" % (hits, misses))

Converted 18723 words (1277 misses)


In [ ]:
len(embeddings_index.keys())

400000

In [ ]:
embedding_matrix.shape

(20002, 100)

# Model

In [ ]:
embedding_layer = Embedding(
    num_tokens,
    embedding_dim,
    embeddings_initializer=keras.initializers.Constant(embedding_matrix),
    trainable=True,
)

In [ ]:
class SLSTMcell(keras.layers.RNN):
    def __init__(self, units=32, window=3, use_bias=True, recurrent_fn=sigmoid, activation_fn=tanh, seq_len=max_len):
        super(SLTMcell, self).__init__()
        self.units = units
        self.use_bias = bias
        self.recurrent_function = recurrent_fn
        self.activation_fn = activation_fn
        self.seq_len = seq_len
      
    def build(self, input_shape):
        input_dim = input_shape[-1]

        self.W = self.add_weight(shape=(input_dim * window, self.units * 7),
                                      name='kernel',
                                      initializer=self.kernel_initializer,
                                      regularizer=self.kernel_regularizer,
                                      constraint=self.kernel_constraint)
        
        self.U = self.add_weight(shape=(input_dim, self.units * 7),
                                      name='kernel',
                                      initializer=self.kernel_initializer,
                                      regularizer=self.kernel_regularizer,
                                      constraint=self.kernel_constraint)
        
        self.V = self.add_weight(shape=(input_dim, self.units * 7),
                                      name='kernel',
                                      initializer=self.kernel_initializer,
                                      regularizer=self.kernel_regularizer,
                                      constraint=self.kernel_constraint)

        if self.use_bias:
            # bias_initializer = self.bias_initializer
            self.bias = self.add_weight(shape=(self.units * 7,),
                                        name='bias',
                                        initializer=bias_initializer,
                                        regularizer=self.bias_regularizer,
                                        constraint=self.bias_constraint)
        else:
            self.bias = None

        self.W_i = self.W[:, :self.units]
        self.W_l = self.W[:, self.units * 1: self.units * 2]
        self.W_r = self.W[:, self.units * 2: self.units * 3]
        self.W_f = self.W[:, self.units * 3: self.units * 4]
        self.W_s = self.W[:, self.units * 4: self.units * 5]
        self.W_o = self.W[:, self.units * 5: self.units * 6]
        self.W_u = self.W[:, self.units * 6:]
        
        self.U_i = self.U[:, :self.units]
        self.U_l = self.U[:, self.units * 1: self.units * 2]
        self.U_r = self.U[:, self.units * 2: self.units * 3]
        self.U_f = self.U[:, self.units * 3: self.units * 4]
        self.U_s = self.U[:, self.units * 4: self.units * 5]
        self.U_o = self.U[:, self.units * 5: self.units * 6]
        self.U_u = self.U[:, self.units * 6:]
        
        self.V_i = self.V[:, :self.units]
        self.V_l = self.V[:, self.units * 1: self.units * 2]
        self.V_r = self.V[:, self.units * 2: self.units * 3]
        self.V_f = self.V[:, self.units * 3: self.units * 4]
        self.V_s = self.V[:, self.units * 4: self.units * 5]
        self.V_o = self.V[:, self.units * 5: self.units * 6]
        self.V_u = self.V[:, self.units * 6:]

        if self.use_bias:
            self.bias_i = self.bias[:self.units]
            self.bias_l = self.bias[self.units * 1: self.units * 2]
            self.bias_r = self.bias[self.units * 2: self.units * 3]
            self.bias_f = self.bias[self.units * 3: self.units * 4]
            self.bias_s = self.bias[self.units * 4: self.units * 5]
            self.bias_o = self.bias[self.units * 5: self.units * 6]
            self.bias_u = self.bias[self.units * 6:]
        else:
            self.bias_i = None
            self.bias_l = None
            self.bias_r = None
            self.bias_f = None
            self.bias_s = None
            self.bias_o = None
            self.bias_u = None
        self.built = True

   def call(self, inputs, states, training=None):

        H_tm1 = states[:, :self.seq_len + 2]  # previous memory state
        c_tm1 = states[:, self.seq_len + 2:]  # previous carry state

        for i in range(1, self.seq_len + 1):
            x_i = inputs[i]
            x_l = inputs[i]
            x_r = inputs[i]
            x_f = inputs[i]
            x_s = inputs[i]
            x_o = inputs[i]
            x_u = inputs[i]
            Ux_i = K.dot(x_i, self.U_i)
            Ux_l = K.dot(x_l, self.U_l)
            Ux_r = K.dot(x_r, self.U_r)
            Ux_f = K.dot(x_f, self.U_f)
            Ux_s = K.dot(x_s, self.U_s)
            Ux_o = K.dot(x_o, self.U_o)
            Ux_u = K.dot(x_u, self.U_u)
            if self.use_bias:
                Ux_i = K.bias_add(Ux_i, self.bias_i)
                Ux_l = K.bias_add(Ux_l, self.bias_l)
                Ux_r = K.bias_add(Ux_r, self.bias_r)
                Ux_f = K.bias_add(Ux_f, self.bias_f)
                Ux_s = K.bias_add(Ux_s, self.bias_s)
                Ux_o = K.bias_add(Ux_o, self.bias_o)
                Ux_u = K.bias_add(Ux_u, self.bias_u)

            
            csi_tm1_i = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_l = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_r = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_f = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_s = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_o = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            csi_tm1_u = tf.concat((H_tm1[:, i-1], H_tm1[:, i], H_tm1[:, i+1]), axis=0)
            Wcsi_i = K.dot(h_tm1_i, self.W_i)
            Wcsi_l = K.dot(h_tm1_l, self.W_l)
            Wcsi_r = K.dot(h_tm1_r, self.W_r)
            Wcsi_f = K.dot(h_tm1_f, self.W_f)
            Wcsi_s = K.dot(h_tm1_s, self.W_s)
            Wcsi_o = K.dot(h_tm1_o, self.W_o)
            Wcsi_u = K.dot(h_tm1_u, self.W_u)
            
            g_tm1_i = H_tm1[:, self.seq_len + 3]
            g_tm1_l = H_tm1[:, self.seq_len + 3]
            g_tm1_r = H_tm1[:, self.seq_len + 3]
            g_tm1_f = H_tm1[:, self.seq_len + 3]
            g_tm1_s = H_tm1[:, self.seq_len + 3]
            g_tm1_o = H_tm1[:, self.seq_len + 3]
            g_tm1_u = H_tm1[:, self.seq_len + 3]
            Vg_i = K.dot(g_tm1_i, self.V_i)
            Vg_l = K.dot(g_tm1_l, self.V_l)
            Vg_r = K.dot(g_tm1_r, self.V_r)
            Vg_f = K.dot(g_tm1_f, self.V_f)
            Vg_s = K.dot(g_tm1_s, self.V_s)
            Vg_o = K.dot(g_tm1_o, self.V_o)
            Vg_u = K.dot(g_tm1_u, self.V_u)

            i_hat = self.recurrent_activation(Wcsi_i + Ux_i + Vg_i)
            l_hat = self.recurrent_activation(Wcsi_l + Ux_l + Vg_l)
            r_hat = self.recurrent_activation(Wcsi_r + Ux_r + Vg_r)
            f_hat = self.recurrent_activation(Wcsi_f + Ux_f + Vg_f)
            s_hat = self.recurrent_activation(Wcsi_s + Ux_s + Vg_s)

            

            c_hat = f * c_tm1 + i * self.activation(x_c + K.dot(h_tm1_c,
                                                            self.recurrent_kernel_c))
            o_hat = self.recurrent_activation(x_o + K.dot(h_tm1_o,
                                                      self.recurrent_kernel_o))
      
        h = o * self.activation(c)
        return h, [h, c]

/content


In [32]:
x = tf.constant([1,2,3], shape=(1,3))
W = tf.transpose(tf.constant([[1,1,1],[2,2,2]], dtype=tf.float64))
Y = W*2

In [28]:
K.dot(x,W)

InvalidArgumentError: ignored

In [16]:
x = tf.constant([1,2,3], shape=(3,))
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [17]:
l = list(range(20))
print(l[:12],l[12:])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] [12, 13, 14, 15, 16, 17, 18, 19]


In [18]:
tf.concat((x,x), axis=0)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 1, 2, 3], dtype=int32)>

In [33]:
tf.keras.activations.softmax(
    W, axis=-1
)

<tf.Tensor: shape=(3, 2), dtype=float64, numpy=
array([[0.26894142, 0.73105858],
       [0.26894142, 0.73105858],
       [0.26894142, 0.73105858]])>